"""zmiana nazw baz danych

Revision ID: 65fe88f672c3
Revises: c472cd3649fe
Create Date: 2024-03-31 20:33:40.142785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fe88f672c3'
down_revision = 'c472cd3649fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('is_borrowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_name'), ['name'], unique=False)

    op.create_table('authors_books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('borrowing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('borrower_name', sa.String(length=200), nullable=False),
    sa.Column('borrowed_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_shelf', schema=None) as batch_op:
        batch_op.drop_index('ix_book_shelf_author')
        batch_op.drop_index('ix_book_shelf_name')

    op.drop_table('book_shelf')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_index('ix_author_lastname')
        batch_op.drop_index('ix_author_name')
        batch_op.drop_column('book_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index('ix_author_name', ['name'], unique=False)
        batch_op.create_index('ix_author_lastname', ['lastname'], unique=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    op.create_table('book_shelf',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('page_number', sa.INTEGER(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_shelf', schema=None) as batch_op:
        batch_op.create_index('ix_book_shelf_name', ['name'], unique=False)
        batch_op.create_index('ix_book_shelf_author', ['author'], unique=False)

    op.drop_table('borrowing')
    op.drop_table('authors_books')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_name'))

    op.drop_table('book')
    # ### end Alembic commands ###
