"""bookshelf table

Revision ID: af9b117efc11
Revises: 
Create Date: 2024-03-31 20:05:55.941706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9b117efc11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_shelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_shelf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_shelf_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_shelf_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_shelf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_shelf_name'))
        batch_op.drop_index(batch_op.f('ix_book_shelf_author'))

    op.drop_table('book_shelf')
    # ### end Alembic commands ###
